authorized_users:
  - kandrosov
  - aebid
  - ahmad3213
  - abolshov
  - valeriadamante

expected_headers:
  - "@cms-flaf-bot test"
  - "@cms-flaf-bot please test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) please test"

variables:
  HH_bbWW_version: "main"
  FLAF_version: "default"
  Corrections_version: "default"
  HH_bbWW_active: "1"
  HH_bbWW_task: "FLAF.Analysis.tasks.HistPlotTask"
  HH_bbWW_args: "--branches 0 --dataset XtoYHto2B2Wto2B2L2Nu_MX_300_MY_125 --test 1000"
  TEST_TIMEOUT: "4h"

gitlab_url: "https://gitlab.cern.ch/api/v4/projects/210600/trigger/pipeline"
gitlab_branch: "master"
