authorized_users:
  - kandrosov
  - aebid
  - ahmad3213
  - abolshov
  - valeriadamante

expected_headers:
  - "@cms-flaf-bot test"
  - "@cms-flaf-bot please test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) please test"

variables:
  HH_bbWW_version: "main"
  FLAF_version: "default"
  Corrections_version: "default"
  HH_bbWW_active: "1"
  HH_bbWW_task: "FLAF.Analysis.tasks.HistPlotTask"
  HH_bbWW_args: "--branches 0 --test 1000"
  HH_bbWW_eras: "Run3_2022 Run3_2022EE Run3_2023 Run3_2023BPix"
  TEST_TIMEOUT: "4h"

gitlab_url: "https://gitlab.cern.ch/api/v4/projects/210600/trigger/pipeline"
gitlab_branch: "master"
