batch_size: 128
learning_rate: 0.0001
n_epochs: 20
name: nn_p3Hbbp3HWW
topology:
- 256
- 128
- 64
- 64
- 16
- 8
valid_split: 0.2
verbosity: 1
tree_name: 'Events'
jet_observables:
- 'px'
- 'py'
- 'pz' 
- 'E'
- 'btagPNetB' 
- 'PNetRegPtRawCorr'
- 'PNetRegPtRawCorrNeutrino' 
- 'PNetRegPtRawRes'
lep_observables:
- 'px'
- 'py'
- 'pz' 
- 'E'
met_observables:
- 'px'
- 'py'
n_jets: 10
labels:
- 'X_mass'
extra_data:
- 'event'
modulo: 2
train_val: 0
test_val: 1
bb_resolved: True
qq_resolved: True