features:
- lep1_pt
- lep1_phi
- lep1_eta
- lep1_mass
- lep2_pt
- lep2_phi
- lep2_eta
- lep2_mass
- met_pt
- met_phi
highlevelfeatures:
- HT
- dR_dilep
- dR_dibjet
- dR_dilep_dibjet
- dR_dilep_dijet
- dPhi_lep1_lep2
- dPhi_jet1_jet2
- dPhi_MET_dilep
- dPhi_MET_dibjet
- min_dR_lep0_jets
- min_dR_lep1_jets
- MT
- MT2_ll
- MT2_bb
- MT2_blbl
- ll_mass
- CosTheta_bb
listfeatures:
- - centralJet_pt
  - 0
- - centralJet_phi
  - 0
- - centralJet_eta
  - 0
- - centralJet_mass
  - 0
- - centralJet_pt
  - 1
- - centralJet_phi
  - 1
- - centralJet_eta
  - 1
- - centralJet_mass
  - 1
- - centralJet_pt
  - 2
- - centralJet_phi
  - 2
- - centralJet_eta
  - 2
- - centralJet_mass
  - 2
- - centralJet_pt
  - 3
- - centralJet_phi
  - 3
- - centralJet_eta
  - 3
- - centralJet_mass
  - 3
model_setup:
  UseParametric: false
  adv_activation: relu
  adv_grad_factor: 1.0
  adv_learning_rate: 0.0001
  adv_weight_decay: 0.004
  apply_common_gradients: true
  class_activation: tanh
  class_grad_factor: 0.001
  common_activation: tanh
  continue_model: null
  continue_training: false
  dropout: 0.0
  learning_rate: 0.0001
  n_adv_layers: 5
  n_adv_units: 128
  n_class_layers: 5
  n_class_units: 128
  n_common_layers: 10
  n_common_units: 256
  n_epochs: 20
  patience: 100
  use_batch_norm: false
  weight_decay: 0.04
modelname_parity:
- - ResHH_Classifier_parity0
  - (lep1_type > 0) && (lep2_type > 0) && (centralJet_pt.size() > 1) && (event%4 ==
    0)
nClasses: 2
class_names:
  - Signal
  - Background
nParity: 1
parametric_list:
- 250
- 260
- 270
- 280
- 300
- 350
- 450
- 550
- 600
- 650
- 700
- 800
- 1000
- 1200
- 1400
- 1600
- 1800
- 2000
- 2500
- 3000
- 4000
- 5000
use_parametric: false
