analysis: hh_bbww
type: resonant
model:
  parameters: [ MX ]
  param_dependent_bkg: false
  # input_file_pattern: SL_DNN_m${MX}_vs_HME/SL_DNN_m${MX}_vs_HME.root
  input_file_pattern: DeepHME_mass.root
hist_bins: [ 0.0, 250.0, 310.0, 390.0, 440.0, 490.0, 540.0, 620.0, 670.0, 740.0, 870.0, 990.0, 2500.0 ]
signalFractionForRelevantBins: 0.2
eras:
  # - Run3_2022
  # - Run3_2022EE
  # - Run3_2023
  - Run3_2023BPix
channels:
  - mu
  - e
categories:
  - SR/res2b
  - SR/boosted
  - SR/recovery
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: XtoHHto2B2W_1L_${MX} # GluGluToRadion2L_${MX}
    hist_name: XtoHHto2B2W_1L_${MX} # GluGluToRadion2L_${MX}
    param_values: [ 300, 400, 500, 550, 600, 650, 700, 800, 900, 1000 ]
    is_signal: true
    channels:
      - e
      - mu
  # want to make that work
  - process: XtoHHto2B2W_2L_${MX} # GluGluToRadion2L_${MX} 
    hist_name: XtoHHto2B2W_2L_${MX} # GluGluToRadion2L_${MX}
    param_values: [ 300, 400, 500, 550, 600, 650, 700, 800, 900, 1000 ]
    is_signal: true
    channels:
      - eE
      - eMu
      - muMu
  - TT
  # - DY
  # - VV
  - ST
  - W
  # - Other
uncertainties:
  - name: lumi_13p6TeV
    type: lnN
    value: 0.014 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3


  # - name: MuonID_TightID
  - name: CMS_eff_m_id
    type: shape
  # - name: MuonID_TightIDIso
  - name: CMS_eff_m_id_iso
    type: shape
  - name: EleID_TightIDIso
    type: shape

  - name: SingleEleTrg
    type: shape
  - name: SingleMuonTrg
    type: shape


  - name: CMS_pileup
    type: shape


  - name: CMS_scale_j
    type: shape
  - name: CMS_res_j
    type: shape
  - name: CMS_scale_e
    type: shape


  # For multiple values, Konstantin says do [ down, up ]
  - name: QCD_scale_TT
    type: lnN
    processes:
      - TTno4Q
    value: [ -0.036, 0.025 ] # TT XS uncertainty in percentage from xsec yaml
    # TT:
    # crossSec: '923.6'
    # reference: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO#Updated_reference_cross_sections
    # unc: +22.6 -33.4 (scale) +/-  22.8 (PDF alphas) -24.6 +25.4 (mass) (to be multiplied by the BR)

  - name: QCD_scale_DY
    type: lnN
    processes:
      - DY
    value: [ -0.011, 0.007 ] # DY XS uncertainty in percentage from xsec yaml
    # DY_NNLO_QCD+NLO_EW:
    # crossSec: 2094.2 * 3
    # reference: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MATRIXCrossSectionsat13p6TeV
    # unc: +0.7% - 1.1%, +- 1.0% PDF alphas

  - name: QCD_scale_ST
    type: lnN
    processes:
      - ST
    value: [ -0.022, +0.022 ]
    # Taken from ST to tW (largest uncertainty on XS) needs to be updated for each decay process later

  - name: QCD_scale_VV
    type: lnN
    processes:
      - VV
    value: 0.005 # This was uncertainty from XSDB

  - name: PDF_alphas
    hasMultipleValues: True
    type: lnN
    value:
      - value: 0.025
        type: lnN
        processes:
          - TT
      - value: 0.01
        type: lnN
        processes:
          - DY
      - value: 0.027
        type: lnN
        processes:
          - ST

  - name: top_mass
    hasMultipleValues: True
    type: lnN
    value:
      - value: [ -0.027, 0.028 ]
        type: lnN
        processes:
          - TT
      - value: [ -0.015, 0.015 ] # Taken from tW for now (largest unc percentage)
        type: lnN
        processes:
          - ST

autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1
